Database [
  {
    Id: 1,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: null,
    GroupId: 2,
    UserId: null,
    RootMenuId: 1,
    Type: 'rootmenu',
    Name: null,
    MenuKey: null,
    MenuLabel: null,
    MenuLink: null,
    MenuType: null,
    RootMenuKey: 'warehouse',
    RootMenuLabel: 'Warehouse Management',
    RootMenuIcon: 'ContainerOutlined',
    RootMenuLink: '/u/warehouse',
    RootMenuUtilities: true
  },
  {
    Id: 2,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: null,
    GroupId: 2,
    UserId: null,
    RootMenuId: 2,
    Type: 'rootmenu',
    Name: null,
    MenuKey: null,
    MenuLabel: null,
    MenuLink: null,
    MenuType: null,
    RootMenuKey: 'users',
    RootMenuLabel: 'USERS',
    RootMenuIcon: 'TeamOutlined',
    RootMenuLink: '/u/add',
    RootMenuUtilities: true
  },
  {
    Id: 3,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: null,
    GroupId: 2,
    UserId: null,
    RootMenuId: 3,
    Type: 'rootmenu',
    Name: null,
    MenuKey: null,
    MenuLabel: null,
    MenuLink: null,
    MenuType: null,
    RootMenuKey: 'system_settings',
    RootMenuLabel: 'System Settings',
    RootMenuIcon: 'SettingOutlined',
    RootMenuLink: '/u/add',
    RootMenuUtilities: true
  },
  {
    Id: 4,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 1,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'warehouse',
    MenuLabel: 'WAREHOUSING',
    MenuLink: '/u/warehouse/warehousing',
    MenuType: 'submenu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 5,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 2,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'warehousing-1-1',
    MenuLabel: 'BARCODE PRINT',
    MenuLink: '/u/warehouse/warehousing/barcode-print',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 6,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 3,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'warehousing-1-2',
    MenuLabel: 'BARCODE CHANGE',
    MenuLink: '/u/warehouse/warehousing/barcode-change',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 7,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 4,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'warehousing-1-3',
    MenuLabel: 'BARCODE CONFIRM',
    MenuLink: '/u/warehouse/warehousing/barcode-confirm',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 8,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 5,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'warehouse',
    MenuLabel: 'KITTING',
    MenuLink: '/u/warehouse/kitting',
    MenuType: 'submenu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 9,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 6,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'kitting-1-1',
    MenuLabel: 'CONFIRM',
    MenuLink: '/u/warehouse/kitting/confirm',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 10,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 7,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'kitting-1-2',
    MenuLabel: 'KITTING OUT',
    MenuLink: '/u/warehouse/kitting/kitting-out',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 11,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 8,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'kitting-1-3',
    MenuLabel: '1D TO 2D PRINT',
    MenuLink: '/u/warehouse/kitting/1d-to-2d-print',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 12,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 9,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'warehouse',
    MenuLabel: 'MATERIAL',
    MenuLink: '/u/warehouse/material',
    MenuType: 'submenu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 13,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 10,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'material-1-1',
    MenuLabel: 'DELIVERY LIST',
    MenuLink: '/u/warehouse/material/delivery-list',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 14,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 11,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'material-1-2',
    MenuLabel: 'WAITING IQC STOCK IN',
    MenuLink: '/u/warehouse/material/waiting-iqc-stock-in/none',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 15,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 12,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'material-1-3',
    MenuLabel: 'WAITING IQC STOCK STATUS',
    MenuLink: '/u/warehouse/material/waiting-iqc-stock-status',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 16,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 13,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'material-1-4',
    MenuLabel: 'STOCK OUT REQUEST',
    MenuLink: '/u/warehouse/material/stock-out-request',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 17,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 14,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'material-1-5',
    MenuLabel: 'STOCK OUT (FIFO)',
    MenuLink: '/u/warehouse/material/stock-out-fifo',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 18,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 15,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'material-1-6',
    MenuLabel: 'MATERIAL STOCK IN',
    MenuLink: '/u/warehouse/material/material-stock-in',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 19,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 16,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'material-1-7',
    MenuLabel: 'CONVERT YYYYMM',
    MenuLink: '/u/warehouse/material/convert-yyyymm',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 20,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 17,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'material-1-8',
    MenuLabel: 'MATERIAL STOCK IN (BULKID)',
    MenuLink: '/u/warehouse/material/material-stock-in-bulkid',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 21,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 18,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'users',
    MenuLabel: 'USERS',
    MenuLink: '/u/add',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 22,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 19,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'system_settings',
    MenuLabel: 'Users',
    MenuLink: '/u/system_settings/users',
    MenuType: 'submenu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 23,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 20,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'user_management-1-1',
    MenuLabel: 'User Management',
    MenuLink: '/u/system_settings/users/user-management',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 24,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 21,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'user_management-1-2',
    MenuLabel: 'Role Management',
    MenuLink: '/u/system_settings/users/role-management',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 25,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 22,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'system_settings',
    MenuLabel: 'Technique',
    MenuLink: '/u/system_settings/technique',
    MenuType: 'submenu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 26,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 23,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'technique-1-1',
    MenuLabel: 'Root Menu',
    MenuLink: '/u/system_settings/technique/root-menu',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 27,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 24,
    GroupId: 2,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'technique-1-2',
    MenuLabel: 'Menu items',
    MenuLink: '/u/system_settings/technique/menu-items',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 577,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: null,
    GroupId: 1,
    UserId: null,
    RootMenuId: 1,
    Type: 'rootmenu',
    Name: null,
    MenuKey: null,
    MenuLabel: null,
    MenuLink: null,
    MenuType: null,
    RootMenuKey: 'warehouse',
    RootMenuLabel: 'Warehouse Management',
    RootMenuIcon: 'ContainerOutlined',
    RootMenuLink: '/u/warehouse',
    RootMenuUtilities: true
  },
  {
    Id: 578,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: null,
    GroupId: 1,
    UserId: null,
    RootMenuId: 2,
    Type: 'rootmenu',
    Name: null,
    MenuKey: null,
    MenuLabel: null,
    MenuLink: null,
    MenuType: null,
    RootMenuKey: 'users',
    RootMenuLabel: 'USERS',
    RootMenuIcon: 'TeamOutlined',
    RootMenuLink: '/u/add',
    RootMenuUtilities: true
  },
  {
    Id: 579,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: null,
    GroupId: 1,
    UserId: null,
    RootMenuId: 3,
    Type: 'rootmenu',
    Name: null,
    MenuKey: null,
    MenuLabel: null,
    MenuLink: null,
    MenuType: null,
    RootMenuKey: 'system_settings',
    RootMenuLabel: 'System Settings',
    RootMenuIcon: 'SettingOutlined',
    RootMenuLink: '/u/add',
    RootMenuUtilities: true
  },
  {
    Id: 580,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: null,
    GroupId: 1,
    UserId: null,
    RootMenuId: 1,
    Type: 'rootmenu',
    Name: null,
    MenuKey: null,
    MenuLabel: null,
    MenuLink: null,
    MenuType: null,
    RootMenuKey: 'warehouse',
    RootMenuLabel: 'Warehouse Management',
    RootMenuIcon: 'ContainerOutlined',
    RootMenuLink: '/u/warehouse',
    RootMenuUtilities: true
  },
  {
    Id: 581,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: null,
    GroupId: 1,
    UserId: null,
    RootMenuId: 2,
    Type: 'rootmenu',
    Name: null,
    MenuKey: null,
    MenuLabel: null,
    MenuLink: null,
    MenuType: null,
    RootMenuKey: 'users',
    RootMenuLabel: 'USERS',
    RootMenuIcon: 'TeamOutlined',
    RootMenuLink: '/u/add',
    RootMenuUtilities: true
  },
  {
    Id: 582,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: null,
    GroupId: 1,
    UserId: null,
    RootMenuId: 3,
    Type: 'rootmenu',
    Name: null,
    MenuKey: null,
    MenuLabel: null,
    MenuLink: null,
    MenuType: null,
    RootMenuKey: 'system_settings',
    RootMenuLabel: 'System Settings',
    RootMenuIcon: 'SettingOutlined',
    RootMenuLink: '/u/add',
    RootMenuUtilities: true
  },
  {
    Id: 583,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 1,
    GroupId: 1,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'warehouse',
    MenuLabel: 'WAREHOUSING',
    MenuLink: '/u/warehouse/warehousing',
    MenuType: 'submenu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 584,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 2,
    GroupId: 1,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'warehousing-1-1',
    MenuLabel: 'BARCODE PRINT',
    MenuLink: '/u/warehouse/warehousing/barcode-print',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 585,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 3,
    GroupId: 1,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'warehousing-1-2',
    MenuLabel: 'BARCODE CHANGE',
    MenuLink: '/u/warehouse/warehousing/barcode-change',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  },
  {
    Id: 586,
    View: false,
    Edit: false,
    Create: false,
    Delete: false,
    MenuId: 4,
    GroupId: 1,
    UserId: null,
    RootMenuId: null,
    Type: 'menu',
    Name: null,
    MenuKey: 'warehousing-1-3',
    MenuLabel: 'BARCODE CONFIRM',
    MenuLink: '/u/warehouse/warehousing/barcode-confirm',
    MenuType: 'menu',
    RootMenuKey: null,
    RootMenuLabel: null,
    RootMenuIcon: null,
    RootMenuLink: null,
    RootMenuUtilities: null
  }
]
