masterCheckResult [
  {
    WorkingTag: 'A',
    IDX_NO: 1,
    DataSeq: 1,
    Selected: 1,
    MessageType: null,
    Status: 0,
    Result: null,
    ROW_IDX: null,
    IsChangedMst: null,
    MatOutSeq: 37913,
    FactUnit: 3,
    MatOutNo: '202412100034',
    MatOutDate: '20241210',
    UseType: 6044001,
    MatOutType: 0,
    IsOutSide: '0',
    OutWHSeq: 0,
    InWHSeq: 343,
    EmpSeq: 0,
    Remark: '',
    OutWHName: null,
    InWHName: null,
    EmpName: null,
    SupplyContCustSeq: null,
    FactUnitName: null,
    Consignee: null,
    SupplyContCustName: null
  }
]