const data = [{
    "Id": 587,
    "View": true,
    "Edit": false,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 1,
    "Type": "menu",
    "Name": null,
    "MenuKey": "warehouse",
    "MenuLabel": "WAREHOUSING",
    "MenuLink": "/u/warehouse/warehousing",
    "MenuType": "submenu",
    "MenuRootId": 1,
    "MenuSubRootId": null
  },
  {
    "Id": 588,
    "View": false,
    "Edit": true,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 2,
    "Type": "menu",
    "Name": null,
    "MenuKey": "warehousing-1-1",
    "MenuLabel": "BARCODE PRINT",
    "MenuLink": "/u/warehouse/warehousing/barcode-print",
    "MenuType": "menu",
    "MenuRootId": null,
    "MenuSubRootId": 1
  },
  {
    "Id": 589,
    "View": false,
    "Edit": false,
    "Create": true,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 3,
    "Type": "menu",
    "Name": null,
    "MenuKey": "warehousing-1-2",
    "MenuLabel": "BARCODE CHANGE",
    "MenuLink": "/u/warehouse/warehousing/barcode-change",
    "MenuType": "menu",
    "MenuRootId": null,
    "MenuSubRootId": 1
  },
  {
    "Id": 590,
    "View": false,
    "Edit": false,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 4,
    "Type": "menu",
    "Name": null,
    "MenuKey": "warehousing-1-3",
    "MenuLabel": "BARCODE CONFIRM",
    "MenuLink": "/u/warehouse/warehousing/barcode-confirm",
    "MenuType": "menu",
    "MenuRootId": null,
    "MenuSubRootId": 1
  },
  {
    "Id": 591,
    "View": false,
    "Edit": false,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 5,
    "Type": "menu",
    "Name": null,
    "MenuKey": "warehouse",
    "MenuLabel": "KITTING",
    "MenuLink": "/u/warehouse/kitting",
    "MenuType": "submenu",
    "MenuRootId": 1,
    "MenuSubRootId": null
  },
  {
    "Id": 592,
    "View": false,
    "Edit": false,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 6,
    "Type": "menu",
    "Name": null,
    "MenuKey": "kitting-1-1",
    "MenuLabel": "CONFIRM",
    "MenuLink": "/u/warehouse/kitting/confirm",
    "MenuType": "menu",
    "MenuRootId": null,
    "MenuSubRootId": 5
  },
  {
    "Id": 593,
    "View": false,
    "Edit": false,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 7,
    "Type": "menu",
    "Name": null,
    "MenuKey": "kitting-1-2",
    "MenuLabel": "KITTING OUT",
    "MenuLink": "/u/warehouse/kitting/kitting-out",
    "MenuType": "menu",
    "MenuRootId": null,
    "MenuSubRootId": 5
  },
  {
    "Id": 594,
    "View": false,
    "Edit": false,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 8,
    "Type": "menu",
    "Name": null,
    "MenuKey": "kitting-1-3",
    "MenuLabel": "1D TO 2D PRINT",
    "MenuLink": "/u/warehouse/kitting/1d-to-2d-print",
    "MenuType": "menu",
    "MenuRootId": null,
    "MenuSubRootId": 5
  },
  {
    "Id": 595,
    "View": false,
    "Edit": false,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 9,
    "Type": "menu",
    "Name": null,
    "MenuKey": "warehouse",
    "MenuLabel": "MATERIAL",
    "MenuLink": "/u/warehouse/material",
    "MenuType": "submenu",
    "MenuRootId": 1,
    "MenuSubRootId": null
  },
  {
    "Id": 596,
    "View": false,
    "Edit": false,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 10,
    "Type": "menu",
    "Name": null,
    "MenuKey": "material-1-1",
    "MenuLabel": "DELIVERY LIST",
    "MenuLink": "/u/warehouse/material/delivery-list",
    "MenuType": "menu",
    "MenuRootId": null,
    "MenuSubRootId": 9
  },
  {
    "Id": 597,
    "View": false,
    "Edit": false,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 11,
    "Type": "menu",
    "Name": null,
    "MenuKey": "material-1-2",
    "MenuLabel": "WAITING IQC STOCK IN",
    "MenuLink": "/u/warehouse/material/waiting-iqc-stock-in/none",
    "MenuType": "menu",
    "MenuRootId": null,
    "MenuSubRootId": 9
  },
  {
    "Id": 598,
    "View": false,
    "Edit": false,
    "Create": false,
    "Delete": false,
    "GroupId": 2,
    "UserId": null,
    "MenuId": 12,
    "Type": "menu",
    "Name": null,
    "MenuKey": "material-1-3",
    "MenuLabel": "WAITING IQC STOCK STATUS",
    "MenuLink": "/u/warehouse/material/waiting-iqc-stock-status",
    "MenuType": "menu",
    "MenuRootId": null,
    "MenuSubRootId": 9
  },
  
]